apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 8000

---
apiVersion: v1
kind: Service 
metadata:
  name: nginx 
spec: 
  type: NodePort 
  ports: 
    - port: 80
      nodePort: 30000
  selector: 
    name: nginx 